FROM golang:1.26-alpine

WORKDIR /app

# Install git and compile tools if needed
RUN apk add --no-cache git build-base

# Copy dependency configs
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Run entry point directly, applying migrations and seeding first, then starting server
CMD ["sh", "-c", "go run cmd/db/main.go migrate-and-seed && go run cmd/shrimpy/main.go"]
