// A curated, dependency-free set of common unicode emoji for the picker's standard
// tab, grouped by category. Not exhaustive — covers the emoji people actually reach
// for on role/ticket buttons. Each entry has keywords to power search.

export interface UnicodeEmoji {
  char: string;
  keywords: string;
}

export interface EmojiCategory {
  label: string;
  emojis: UnicodeEmoji[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: "Smileys",
    emojis: [
      { char: "😀", keywords: "grin smile happy" },
      { char: "😁", keywords: "grin beam happy" },
      { char: "😂", keywords: "joy laugh tears" },
      { char: "🤣", keywords: "rofl laugh" },
      { char: "😊", keywords: "blush smile" },
      { char: "😍", keywords: "heart eyes love" },
      { char: "😘", keywords: "kiss love" },
      { char: "😎", keywords: "cool sunglasses" },
      { char: "🤩", keywords: "star struck excited" },
      { char: "🥳", keywords: "party celebrate" },
      { char: "😇", keywords: "angel innocent" },
      { char: "🙂", keywords: "slight smile" },
      { char: "😉", keywords: "wink" },
      { char: "😌", keywords: "relieved calm" },
      { char: "😴", keywords: "sleep tired" },
      { char: "🤔", keywords: "thinking hmm" },
      { char: "🤨", keywords: "raised eyebrow suspicious" },
      { char: "😐", keywords: "neutral meh" },
      { char: "😢", keywords: "cry sad" },
      { char: "😭", keywords: "sob cry sad" },
      { char: "😡", keywords: "angry mad rage" },
      { char: "🤯", keywords: "mind blown shock" },
      { char: "😱", keywords: "scream shock fear" },
      { char: "🥺", keywords: "pleading puppy eyes" },
      { char: "😅", keywords: "sweat smile nervous" },
      { char: "🙃", keywords: "upside down silly" },
      { char: "🤗", keywords: "hug" },
      { char: "🤪", keywords: "zany crazy" },
      { char: "😜", keywords: "tongue playful" },
      { char: "🥰", keywords: "love hearts smile" },
    ],
  },
  {
    label: "Gestures & People",
    emojis: [
      { char: "👍", keywords: "thumbs up yes like approve" },
      { char: "👎", keywords: "thumbs down no dislike" },
      { char: "👌", keywords: "ok perfect" },
      { char: "✌️", keywords: "peace victory" },
      { char: "🤞", keywords: "fingers crossed luck" },
      { char: "🤝", keywords: "handshake deal agree" },
      { char: "👏", keywords: "clap applause" },
      { char: "🙌", keywords: "raise hands praise" },
      { char: "🙏", keywords: "pray thanks please" },
      { char: "💪", keywords: "muscle strong flex" },
      { char: "👋", keywords: "wave hello hi bye" },
      { char: "🤚", keywords: "raised hand stop" },
      { char: "✋", keywords: "hand high five stop" },
      { char: "👀", keywords: "eyes look watch" },
      { char: "🫡", keywords: "salute respect" },
      { char: "🧑‍💻", keywords: "developer coder tech" },
      { char: "🕵️", keywords: "detective spy" },
      { char: "💂", keywords: "guard" },
      { char: "🦸", keywords: "hero superhero" },
      { char: "🧙", keywords: "wizard mage" },
    ],
  },
  {
    label: "Symbols",
    emojis: [
      { char: "❤️", keywords: "heart love red" },
      { char: "🧡", keywords: "heart orange" },
      { char: "💛", keywords: "heart yellow" },
      { char: "💚", keywords: "heart green" },
      { char: "💙", keywords: "heart blue" },
      { char: "💜", keywords: "heart purple" },
      { char: "🖤", keywords: "heart black" },
      { char: "🤍", keywords: "heart white" },
      { char: "⭐", keywords: "star favorite" },
      { char: "🌟", keywords: "star glow sparkle" },
      { char: "✨", keywords: "sparkles shiny new" },
      { char: "🔥", keywords: "fire lit hot" },
      { char: "💯", keywords: "hundred perfect score" },
      { char: "✅", keywords: "check yes done tick" },
      { char: "❌", keywords: "cross no wrong x" },
      { char: "❓", keywords: "question help" },
      { char: "❗", keywords: "exclamation important" },
      { char: "⚠️", keywords: "warning caution" },
      { char: "🔔", keywords: "bell notify alert" },
      { char: "🔒", keywords: "lock closed secure" },
      { char: "🔓", keywords: "unlock open" },
      { char: "🏆", keywords: "trophy win award" },
      { char: "🎖️", keywords: "medal award" },
      { char: "🎗️", keywords: "ribbon award" },
      { char: "💎", keywords: "gem diamond premium" },
      { char: "👑", keywords: "crown king vip" },
      { char: "🚫", keywords: "no forbidden ban" },
      { char: "♻️", keywords: "recycle" },
    ],
  },
  {
    label: "Objects & Activities",
    emojis: [
      { char: "🎮", keywords: "game controller gaming" },
      { char: "🕹️", keywords: "joystick arcade game" },
      { char: "🎨", keywords: "art palette paint design" },
      { char: "🎵", keywords: "music note song" },
      { char: "🎧", keywords: "headphones music audio" },
      { char: "🎤", keywords: "mic sing karaoke" },
      { char: "📢", keywords: "announce megaphone loud" },
      { char: "📣", keywords: "megaphone cheer" },
      { char: "🛠️", keywords: "tools build dev repair" },
      { char: "⚙️", keywords: "gear settings config" },
      { char: "🔧", keywords: "wrench fix tool" },
      { char: "💻", keywords: "laptop computer code" },
      { char: "🖥️", keywords: "desktop computer" },
      { char: "📱", keywords: "phone mobile" },
      { char: "💡", keywords: "idea bulb light" },
      { char: "📌", keywords: "pin pinned" },
      { char: "📎", keywords: "paperclip attach" },
      { char: "📚", keywords: "books read library" },
      { char: "✏️", keywords: "pencil write edit" },
      { char: "🎫", keywords: "ticket admit" },
      { char: "🎟️", keywords: "tickets admission" },
      { char: "💰", keywords: "money bag cash" },
      { char: "🛒", keywords: "cart shop buy" },
      { char: "⚽", keywords: "soccer football sport" },
      { char: "🏀", keywords: "basketball sport" },
      { char: "🎯", keywords: "target dart goal" },
      { char: "🚀", keywords: "rocket launch fast" },
      { char: "🎉", keywords: "party celebrate tada" },
      { char: "🎁", keywords: "gift present" },
    ],
  },
  {
    label: "Nature & Food",
    emojis: [
      { char: "🦐", keywords: "shrimp shrimpy" },
      { char: "🐙", keywords: "octopus" },
      { char: "🐢", keywords: "turtle" },
      { char: "🐱", keywords: "cat kitten" },
      { char: "🐶", keywords: "dog puppy" },
      { char: "🦊", keywords: "fox" },
      { char: "🐸", keywords: "frog" },
      { char: "🦋", keywords: "butterfly" },
      { char: "🌈", keywords: "rainbow pride" },
      { char: "🌊", keywords: "wave water ocean" },
      { char: "🌸", keywords: "blossom flower" },
      { char: "🌵", keywords: "cactus" },
      { char: "🍀", keywords: "clover luck" },
      { char: "🍕", keywords: "pizza food" },
      { char: "🍔", keywords: "burger food" },
      { char: "🍟", keywords: "fries food" },
      { char: "🍩", keywords: "donut sweet" },
      { char: "☕", keywords: "coffee tea drink" },
      { char: "🍺", keywords: "beer drink" },
      { char: "🎂", keywords: "cake birthday" },
    ],
  },
  {
    label: "Flags",
    emojis: [
      { char: "🏳️", keywords: "white flag surrender" },
      { char: "🏴", keywords: "black flag" },
      { char: "🏁", keywords: "checkered flag race finish" },
      { char: "🚩", keywords: "triangular flag red" },
      { char: "🏳️‍🌈", keywords: "rainbow flag pride lgbt" },
      { char: "🏳️‍⚧️", keywords: "transgender flag trans pride" },
      { char: "🇺🇳", keywords: "united nations flag" },
      { char: "🇺🇸", keywords: "united states usa america flag" },
      { char: "🇬🇧", keywords: "united kingdom uk britain flag" },
      { char: "🇨🇦", keywords: "canada flag" },
      { char: "🇲🇽", keywords: "mexico flag" },
      { char: "🇧🇷", keywords: "brazil flag" },
      { char: "🇦🇷", keywords: "argentina flag" },
      { char: "🇫🇷", keywords: "france flag" },
      { char: "🇩🇪", keywords: "germany flag" },
      { char: "🇪🇸", keywords: "spain flag" },
      { char: "🇮🇹", keywords: "italy flag" },
      { char: "🇵🇹", keywords: "portugal flag" },
      { char: "🇳🇱", keywords: "netherlands flag" },
      { char: "🇸🇪", keywords: "sweden flag" },
      { char: "🇳🇴", keywords: "norway flag" },
      { char: "🇷🇺", keywords: "russia flag" },
      { char: "🇺🇦", keywords: "ukraine flag" },
      { char: "🇵🇱", keywords: "poland flag" },
      { char: "🇹🇷", keywords: "turkey flag" },
      { char: "🇮🇳", keywords: "india flag" },
      { char: "🇨🇳", keywords: "china flag" },
      { char: "🇯🇵", keywords: "japan flag" },
      { char: "🇰🇷", keywords: "south korea flag" },
      { char: "🇮🇩", keywords: "indonesia flag" },
      { char: "🇵🇭", keywords: "philippines flag" },
      { char: "🇻🇳", keywords: "vietnam flag" },
      { char: "🇸🇬", keywords: "singapore flag" },
      { char: "🇲🇾", keywords: "malaysia flag" },
      { char: "🇹🇭", keywords: "thailand flag" },
      { char: "🇸🇦", keywords: "saudi arabia flag" },
      { char: "🇦🇪", keywords: "united arab emirates uae flag" },
      { char: "🇿🇦", keywords: "south africa flag" },
      { char: "🇳🇬", keywords: "nigeria flag" },
      { char: "🇪🇬", keywords: "egypt flag" },
      { char: "🇦🇺", keywords: "australia flag" },
      { char: "🇳🇿", keywords: "new zealand flag" },
    ],
  },
];
